In [ ]:
# !pip install numpy
# conda install numpy

In [8]:
import numpy as np

In [9]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [10]:
np.array(my_list)

array([1, 2, 3])

In [11]:
my_array = np.array(my_list)  # array metodu ile tek boyutlu liste
my_array

array([1, 2, 3])

In [12]:
my_list =[[1, 2, 3], [1, 2, 3], [1, 2, 3]]
my_list

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [13]:
my_array = np.array(my_list)  # array metodu ile tek boyutlu liste
my_array

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [14]:
my_list =[[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]], [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]]
my_list

[[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]],
 [[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]]

In [15]:
my_array = np.array(my_list)  # 3 boyutlu liste
my_array

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [16]:
np.array(((1, 2, 3, 4), (1, 2, 3, 4)))

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [21]:
for i in range(0,10,2):  
    print(i)

0
2
4
6
8


In [22]:
mylist = []

for i in range(0,10,2):
    mylist.append(i)
print(mylist)
print(mylist[3])

[0, 2, 4, 6, 8]
6


In [23]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [24]:
np.arange(0, 11, 5)

array([ 0,  5, 10])

In [32]:
np.random.randint(1907)  # random degerler integers olarak gelir

1668

In [33]:
rand_arr

NameError: name 'rand_arr' is not defined

In [34]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

In [35]:
x, y, z

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [36]:
np.concatenate([x, y, z], axis=0).reshape(1,3)  # alt alta icin daha güzel yazim sekli

ValueError: cannot reshape array of size 9 into shape (1,3)

In [37]:
np.concatenate([x, y, z], axis=0).reshape(3,3)  # alt alta icin daha güzel yazim sekli

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a = np.random.randint(10, size = (2, 3))
a

array([[0, 5, 2],
       [8, 3, 1]])

In [48]:
b = np.random.randint(10, size = (2, 3))
b

array([[4, 3, 6],
       [2, 1, 7]])

In [56]:
np.concatenate([a,b])

array([[0, 5, 2],
       [8, 3, 1],
       [4, 3, 6],
       [2, 1, 7]])

In [1]:
5*4

20